# Generated by Django 5.2.3 on 2025-07-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trabajador',
            old_name='apellido',
            new_name='cargo',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='cedula',
        ),
        migrations.AddField(
            model_name='trabajador',
            name='telefono',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='codigo_empleado',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='trabajadores/'),
        ),
    ]
